
# This is a basic workflow to help you get started with Actions

name: Funny Gif
on:
  issues:
  push:
    types: [opened]

jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Funny Gif
        uses: Marta83/funny-comment-action@v2.1
        id: FunnyComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_KEY: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
